# Generated by Django 4.1.7 on 2023-03-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(default=1, max_length=20, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(default='1', max_length=20, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
