# Generated by Django 4.1.7 on 2023-03-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rename_image_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['sequential_number'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterField(
            model_name='image',
            name='sequential_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Порядковый номер'),
        ),
    ]
